### PR TITLE
App icon

### PR DESCRIPTION
**Pull request by juliendonck**
Trying to add the app icon. Apparently on mac you have to add it manually in developer mode. It only renders when you build it. Except if you add the icon manually.

Here's the temporary icon btw:

Screenshot 2019-11-04 at 10 04 51

### CODE REVIEW

**Comment by juliendonck** [comment]
@rudolfs updated the icon. FYI

**Comment by rudolfs** [comment]
Verify that it works on:
- [ ] macOS
- [ ] Linux

Steps to verify:
1. run `yarn dist`
2. open the package in `dist/` and check the app icon:
    - when the app is running
    - executable icon
    - package icon

**Comment by rudolfs** [comment]
- unmounted dmg:
Screenshot 2019-11-04 at 11 13 33

- dmg finder/installer:
Screenshot 2019-11-04 at 11 13 46

- mounted dmg:
Screenshot 2019-11-04 at 11 13 59

- dock:
Screenshot 2019-11-04 at 11 14 07

- about dialog:
Screenshot 2019-11-04 at 11 14 24

**Comment by rudolfs** [comment]
Correct: it's not working on Linux. And it is in the scope of this issue. Will work on a fix.

**Comment by juliendonck** [comment]
I think for linux you might need png's and stuff, no? Let me know, cause I can add these

**Comment by rudolfs** [comment]
Seems to work now on Linux.

- Appimage:
Screenshot 2019-11-05 at 10 39 35

- Sidebar:
Screenshot 2019-11-05 at 11 33 56

- Taskbar:
Screenshot 2019-11-05 at 11 34 01

**Comment by rudolfs** [comment]
@juliendonck it's probably fine for now, but FYI: Linux makes the task-bar image grayscale and very small, I don't know if there is a way to tweak it.

**Comment by rudolfs** [comment]
Squashed and force-pushed, because some of your commits weren't verified.

**Pull request merged**
